spring.application.name=url-shortner-practice
spring.datasource.url=jdbc:postgresql://localhost:5432/short-url-practice
spring.datasource.username=postgres
spring.datasource.password=790375
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

jwt.secret=2d7b75285f45746478be2285476cec29727127ef7cb9e488b81ff7aefb358721313d39b6bdd30955077efcf11fa39652b30243850d3bae9ccf7d04011156d26c2b09794eb4c16c5802c11589d6200aa731162aabb49a78ea28c2e3ca7f09317e
#jwt.expiration=1000 * 120 * 120 * 10

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.web.servlet=TRACE